package astrotibs.asmc;

import java.io.File;

import astrotibs.asmc.config.GeneralConfig;
import astrotibs.asmc.proxy.CommonProxy;
import astrotibs.asmc.sounds.SoundEventHandler;
import astrotibs.asmc.utility.Reference;
import astrotibs.asmc.version.DevVersionWarning;
import astrotibs.asmc.version.VersionChecker;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.common.MinecraftForge;

/*
 * Testing sword:
 * give @p golden_sword 1 0 {display:{Name:"Un-Instantiator"}, ench:[{id:16,lvl:1000},{id:34,lvl:99}]}
 * Loot level 3: {id:21,lvl:3}
 */

@Mod(	
		modid = Reference.MOD_ID,
		name = Reference.MOD_NAME,
		version = Reference.VERSION,
		guiFactory = Reference.GUI_FACTORY
		)
public final class ModASMC
{
	
	@SidedProxy(clientSide = Reference.CLIENT_PROXY, serverSide = Reference.SERVER_PROXY)
	public static CommonProxy PROXY;	

	public static File configDirectory;
	
	@Instance(Reference.MOD_ID)
	public static ModASMC instance;

	// Version checking instance
	public static VersionChecker versionChecker = new VersionChecker();
	public static boolean haveWarnedVersionOutOfDate = false;
	public static boolean devVersionWarned = false;
	

	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		configDirectory = new File(event.getModConfigurationDirectory(), Reference.MOD_ID+".cfg");
		GeneralConfig.init(configDirectory);//new File(configDirectory, "general.cfg"));

    	
    	// Version check monitor
        if (GeneralConfig.versionChecker) {FMLCommonHandler.instance().bus().register(versionChecker);}
        if ((Reference.VERSION).contains("DEV")) {FMLCommonHandler.instance().bus().register(new DevVersionWarning());}
        
        // --- Listener registry --- //
 		MinecraftForge.EVENT_BUS.register(new SoundEventHandler());
 		FMLCommonHandler.instance().bus().register(new SoundEventHandler());
 		
		// The following overrides the mcmod.info file!
		// Adapted from Jabelar's Magic Beans:
		// https://github.com/jabelar/MagicBeans-1.7.10/blob/e48456397f9c6c27efce18e6b9ad34407e6bc7c7/src/main/java/com/blogspot/jabelarminecraft/magicbeans/MagicBeans.java
        event.getModMetadata().autogenerated = false ; // stops it from complaining about missing mcmod.info
        
        event.getModMetadata().name = 			// name 
        		EnumChatFormatting.LIGHT_PURPLE + 
        		Reference.MOD_NAME;
        
        event.getModMetadata().version = 		// version 
        		Reference.VERSION;
        
        event.getModMetadata().credits = 		// credits 
        		EnumChatFormatting.AQUA +
        		"Sound effects by Mojang";
        
        event.getModMetadata().authorList.clear();
        event.getModMetadata().authorList.add(  // authorList - added as a list
        		EnumChatFormatting.BLUE +
        		"AstroTibs");
        
        event.getModMetadata().url = EnumChatFormatting.GRAY +
        		Reference.URL;
        
        event.getModMetadata().description = 	// description
	       		EnumChatFormatting.YELLOW +
	       		"Backports Minecraft sounds to older versions";
        
        event.getModMetadata().logoFile = "assets/"+Reference.MOD_ID+"/asmc_banner.png";

	}
	
	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		PROXY.init(event);
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event)
	{
		
	}
}
